### ISSUE TITLE
AddVMATBeam throwing error

### ISSUE THREAD

**Issue by tkstevens** [VarianAPIs/PyESAPI#13]
Trying to create a new beam with `PlanSetup.AddVMATBeam` triggers an Eclipse dialog box with the warning: "The following parameters were adjusted to be within machine limits: collimator positions". The only collimator "position" being passed here is the collimator angle, and the warning appears regardless of the _double_ angle given (0, 0.0, 30.0, etc.), after which the given angle appears to be accepted. Note that the resultant beam does not have a tolerance table assigned (which may be related), but there is no where to pass `ToleranceTableLabel` during the `AddVMATBeam` call. Obviously, this interaction with a dialog box is not ideal when batch processing.

**Comment by joecastelo** [comment]
Happens with me as well

**Comment by albie0019** [comment]
Did you guys find @tkstevens a solution to this? I am having this problem in ESAPI (C#).

**Comment by fizxmike** [comment]
For posterity, please see this related thread on ESAPI subreddit:
https://www.reddit.com/r/esapi/comments/i8bbk4/problem_with_message_the_following_parameters/
