### ISSUE TITLE
CopyPlanSetup fails when attempting to copy a plan that is approved

### ISSUE THREAD

**Issue by tkstevens** [VarianAPIs/PyESAPI#14]
Given a Treatment Approved `sourcePlan` in course `sourceCourse`, a new plan can be created with `newPlan=sourceCourse.CopyPlanSetup(sourcePlan)`. However, upon `app.SaveModifications()` an error is produced that mentions "tU_PlanSetup_VaBusinessLogic, Line 694: PlanSetup is approved: Cannot UPDATE PlanSetup. PlanSetupSer: 549944", where 549944 is the Ser of the sourcePlan (and no modifications are being asked of this plan). The workflow runs fine when copying an unapproved plan.

**Comment by fizxmike** [comment]
Unfortunately, copying a plan modifies its history:
https://www.reddit.com/r/esapi/comments/llof82/cannot_save_plansetup_modification/
