### ISSUE TITLE
Plan Uncertainty Doses calculation

### ISSUE THREAD

**Issue by mfizyczka** [VarianAPIs/PyESAPI#20]
Is it possible to specify Plan Uncertainty Parameters using ESAPI / PyESAPI and calculate dose for these plans afterwards?

**Comment by fizxmike** [comment]
Please reference the ESAPI help documentation in Eclipse (question mark in upper right hand side of Eclipse External Beam Planning). You can also reference our [Varian API Book](https://varianapis.github.io/VarianApiBook.pdf) or [ESAPI subreddit](https://www.reddit.com/r/esapi/).
