### ISSUE TITLE
CouchRtn

### ISSUE THREAD

**Issue by ZTnb** [VarianAPIs/PyESAPI#27]
How can I get the couch rotation?

**Comment by fizxmike** [comment]
PyESAPI class structures are identical to ESAPI. So, you can check the help documentation in Eclipse (question mark button on top right of window). You can also [see here](https://github.com/Varian-MedicalAffairsAppliedSolutions/MAAS-BeamDashboardX/blob/b4f264eadd5e17fcaca5548ed7333c5ae1204b78/beam_dashboard_x.py#L53) where we have an example of reading data from control points and putting them into a pandas data frame.

**Comment by fizxmike** [comment]
PyESAPI class structures are identical to ESAPI. So, you can check the help documentation in Eclipse (question mark button on top right of window). We have the [Varian API Book](https://varianapis.github.io/VarianApiBook.pdf) you can reference as well. You can also [see here](https://github.com/Varian-MedicalAffairsAppliedSolutions/MAAS-BeamDashboardX/blob/b4f264eadd5e17fcaca5548ed7333c5ae1204b78/beam_dashboard_x.py#L53) where we have an example of reading data from control points and putting them into a pandas data frame.

**Comment by fizxmike** [comment]
PyESAPI class structures are identical to ESAPI. So, you can check the help documentation in Eclipse (question mark button on top right of window). We have the [Varian API Book](https://varianapis.github.io/VarianApiBook.pdf) you can reference as well. You can also [see here](https://github.com/Varian-MedicalAffairsAppliedSolutions/MAAS-BeamDashboardX/blob/b4f264eadd5e17fcaca5548ed7333c5ae1204b78/beam_dashboard_x.py#L53) where we have an example of reading data from control points and putting them into a pandas data frame.

**Comment by fizxmike** [comment]
Added a section in README listing [additional resources](https://github.com/VarianAPIs/PyESAPI?tab=readme-ov-file#additional-resources)
