### ISSUE TITLE
How to use the pyesapi with the pythonnet 3.0.3

### ISSUE THREAD

**Issue by vinaysaini94** [VarianAPIs/PyESAPI#28]
When I run the command `import pyesapi` on my test box system, I get the following error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Varian\anaconda3\envs\Python18062024\lib\site-packages\pyesapi\__init__.py", line 83, in <module>
    from VMS.TPS.Common.Model.Types import *
ModuleNotFoundError: No module named 'VMS.TPS.Common.Model.Types'
```

Any solutions for this issue? I am using the .NET Framework 4.3 and Eclipse version 15.6. Any suggestions for running pyesapi with pythonnet 3.0.3?

Thanks.

**Comment by fizxmike** [comment]
Hi @vinaysaini94,
I've updated PyESAPI to include pywin32 as a dependency... perhaps this might help? Try re-installing PyESAPI using pip and it should get installed automatically:
`pip uninstall pyesapi`
`pip install --upgrade pyesapi`

**Comment by LuisOlivaresJ** [comment]
See https://github.com/VarianAPIs/PyESAPI/issues/26#issuecomment-2261377820
