### ISSUE TITLE
PyESAPI on Citrix

### ISSUE THREAD

**Issue by pgallego25** [VarianAPIs/PyESAPI#4]
Is there any way to run PyESAPI over an Aria citrix based implementation?

Thank you!

**Comment by fizxmike** [comment]
Assuming it's not a clinical environment, absolutely! You install an anaconda3 environment on the Citrix host/Eclipse client (install for "just me" into a well accessable folder/file share location). Then create an ESAPI single file plug-in to launch anaconda prompt and jupyter notebook. If you are interested, I can share those launcher scripts. Some permissions from your sysadmin may be required.

**Comment by zackmorelli** [comment]
Hi Mike,

I am also trying to install PYESAPI in an Aria/Citrix environment. I would be very interested in these launcher scripts and any other information you could provide.

Thank You.

**Comment by pgallego25** [comment]
Hi! it is not possible in a clinical enviroment??

**Comment by fizxmike** [comment]
PyESAPI is intended for research use only (typically on a TBOX).

**Comment by rohitchauhan688** [comment]
Hello, I m working on pyESAPI.
 Can you please let me know, how to transfer the current running database to the TBOX to use it for research with pyESAPI?

**Comment by zackmorelli** [comment]
I think Varian has to update the TBOX by transfering the database from the
clinical system. Not something you can do yourself.

**Comment by Shea1986** [comment]
Hi Mike, for , is pyesapi36 supporting clinical plug-in script (i.e. compile into dll and used in production system)? thank you

**Comment by fizxmike** [comment]
PyESAPI is not supported for clinical use.

**Comment by fizxmike** [comment]
> Hi Mike, for , is pyesapi36 supporting clinical plug-in script (i.e. compile into dll and used in production system)? thank you

PyESAPI is not supported for clinical use.

**Comment by LuisOlivaresJ** [comment]
Hi, 

On my clinic, the TBOX only contains a small test-set of random patients (~100), but I would like to have access to more of them.  Specially for new created "patients" related to phantoms used for QA.

Do you know another approach instead update the TBOX database?

Thanks for your amazing work!

**Comment by fizxmike** [comment]
For posterity,

1. The `CustomScriptExecutable.CreateApplication(...)` function leveraged by PyESAPI is part of clinical ESAPI but only allows read-only access. When database is swited to research mode, you can read and write.
1. Here is an example of "packaging" a PyESAPI-based script to share with fellow researchers: https://github.com/Varian-MedicalAffairsAppliedSolutions/MAAS-BeamDashboardX
